[project]
name = "langchain-documentation-helper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "black>=25.1.0",
    "google-api-core>=2.28.1",
    "grpcio>=1.76.0",
    "isort>=6.0.1",
    "langchain>=0.3.27",
    "langchain-community>=0.3.27",
    "langchain-ollama>=1.0.1",
    "langchain-pinecone>=0.2.11",
    "langchain-tavily>=0.2.15",
    "langchainhub>=0.1.21",
    "pinecone>=7.3.0",
    "python-dotenv>=1.1.1",
    "streamlit>=1.52.2",
    "watchdog>=6.0.0",
]
